### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [criteo/gtm-criteo-loader#1]
https://github.com/criteo/gtm-criteo-loader/blob/436584fccebe8b5b15bc6b99e5d00a5e56c39e0e/template.tpl#L153

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by MarcDillar** [comment]
Very good point indeed, thanks for flagging.
Fixed with commit 5d358a13fc68caad41c1ddef2baa1163fe5c4989.
